#
# Build
#

build { core init core-api-1 drivers/timer }

create_boot_directory

#
# Generate config
#

install_config {
<config>
	<parent-provides>
    <service name="ROM"/>
    <service name="RAM"/>
    <service name="IRQ"/>
    <service name="IO_MEM"/>
    <service name="IO_PORT"/>
    <service name="CAP"/>
    <service name="PD"/>
    <service name="RM"/>
    <service name="CPU"/>
    <service name="LOG"/>
    <service name="SIGNAL"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<start name="core-api-1">
		<resource name="RAM" quantum="3G"/>
	</start>
</config>
}

#
# Boot image
#


build_boot_image { 
                 core 
                 init 
                 core-api-1
}


append qemu_args " -smp 4,cores=4  -m 4G -nographic "

run_genode_until {OK!} 100
